/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ScalpFacialSpringHillTnRouteImport } from './routes/scalp-facial-spring-hill-tn'
import { Route as LuxuryHairSalonSpringHillTnRouteImport } from './routes/luxury-hair-salon-spring-hill-tn'
import { Route as HairAndEstheticServicesSpringHillTnRouteImport } from './routes/hair-and-esthetic-services-spring-hill-tn'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EducationRouteImport } from './routes/education'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as BlondingSpecialistSpringHillTnRouteImport } from './routes/blonding-specialist-spring-hill-tn'
import { Route as BalayageSpringHillTnRouteImport } from './routes/balayage-spring-hill-tn'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ScalpFacialSpringHillTnRoute = ScalpFacialSpringHillTnRouteImport.update({
  id: '/scalp-facial-spring-hill-tn',
  path: '/scalp-facial-spring-hill-tn',
  getParentRoute: () => rootRouteImport,
} as any)
const LuxuryHairSalonSpringHillTnRoute =
  LuxuryHairSalonSpringHillTnRouteImport.update({
    id: '/luxury-hair-salon-spring-hill-tn',
    path: '/luxury-hair-salon-spring-hill-tn',
    getParentRoute: () => rootRouteImport,
  } as any)
const HairAndEstheticServicesSpringHillTnRoute =
  HairAndEstheticServicesSpringHillTnRouteImport.update({
    id: '/hair-and-esthetic-services-spring-hill-tn',
    path: '/hair-and-esthetic-services-spring-hill-tn',
    getParentRoute: () => rootRouteImport,
  } as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const BlondingSpecialistSpringHillTnRoute =
  BlondingSpecialistSpringHillTnRouteImport.update({
    id: '/blonding-specialist-spring-hill-tn',
    path: '/blonding-specialist-spring-hill-tn',
    getParentRoute: () => rootRouteImport,
  } as any)
const BalayageSpringHillTnRoute = BalayageSpringHillTnRouteImport.update({
  id: '/balayage-spring-hill-tn',
  path: '/balayage-spring-hill-tn',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/balayage-spring-hill-tn': typeof BalayageSpringHillTnRoute
  '/blonding-specialist-spring-hill-tn': typeof BlondingSpecialistSpringHillTnRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/education': typeof EducationRoute
  '/gallery': typeof GalleryRoute
  '/hair-and-esthetic-services-spring-hill-tn': typeof HairAndEstheticServicesSpringHillTnRoute
  '/luxury-hair-salon-spring-hill-tn': typeof LuxuryHairSalonSpringHillTnRoute
  '/scalp-facial-spring-hill-tn': typeof ScalpFacialSpringHillTnRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/balayage-spring-hill-tn': typeof BalayageSpringHillTnRoute
  '/blonding-specialist-spring-hill-tn': typeof BlondingSpecialistSpringHillTnRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/education': typeof EducationRoute
  '/gallery': typeof GalleryRoute
  '/hair-and-esthetic-services-spring-hill-tn': typeof HairAndEstheticServicesSpringHillTnRoute
  '/luxury-hair-salon-spring-hill-tn': typeof LuxuryHairSalonSpringHillTnRoute
  '/scalp-facial-spring-hill-tn': typeof ScalpFacialSpringHillTnRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/balayage-spring-hill-tn': typeof BalayageSpringHillTnRoute
  '/blonding-specialist-spring-hill-tn': typeof BlondingSpecialistSpringHillTnRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/education': typeof EducationRoute
  '/gallery': typeof GalleryRoute
  '/hair-and-esthetic-services-spring-hill-tn': typeof HairAndEstheticServicesSpringHillTnRoute
  '/luxury-hair-salon-spring-hill-tn': typeof LuxuryHairSalonSpringHillTnRoute
  '/scalp-facial-spring-hill-tn': typeof ScalpFacialSpringHillTnRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/balayage-spring-hill-tn'
    | '/blonding-specialist-spring-hill-tn'
    | '/booking'
    | '/contact'
    | '/education'
    | '/gallery'
    | '/hair-and-esthetic-services-spring-hill-tn'
    | '/luxury-hair-salon-spring-hill-tn'
    | '/scalp-facial-spring-hill-tn'
    | '/services'
    | '/shop'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/balayage-spring-hill-tn'
    | '/blonding-specialist-spring-hill-tn'
    | '/booking'
    | '/contact'
    | '/education'
    | '/gallery'
    | '/hair-and-esthetic-services-spring-hill-tn'
    | '/luxury-hair-salon-spring-hill-tn'
    | '/scalp-facial-spring-hill-tn'
    | '/services'
    | '/shop'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/balayage-spring-hill-tn'
    | '/blonding-specialist-spring-hill-tn'
    | '/booking'
    | '/contact'
    | '/education'
    | '/gallery'
    | '/hair-and-esthetic-services-spring-hill-tn'
    | '/luxury-hair-salon-spring-hill-tn'
    | '/scalp-facial-spring-hill-tn'
    | '/services'
    | '/shop'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BalayageSpringHillTnRoute: typeof BalayageSpringHillTnRoute
  BlondingSpecialistSpringHillTnRoute: typeof BlondingSpecialistSpringHillTnRoute
  BookingRoute: typeof BookingRoute
  ContactRoute: typeof ContactRoute
  EducationRoute: typeof EducationRoute
  GalleryRoute: typeof GalleryRoute
  HairAndEstheticServicesSpringHillTnRoute: typeof HairAndEstheticServicesSpringHillTnRoute
  LuxuryHairSalonSpringHillTnRoute: typeof LuxuryHairSalonSpringHillTnRoute
  ScalpFacialSpringHillTnRoute: typeof ScalpFacialSpringHillTnRoute
  ServicesRoute: typeof ServicesRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scalp-facial-spring-hill-tn': {
      id: '/scalp-facial-spring-hill-tn'
      path: '/scalp-facial-spring-hill-tn'
      fullPath: '/scalp-facial-spring-hill-tn'
      preLoaderRoute: typeof ScalpFacialSpringHillTnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luxury-hair-salon-spring-hill-tn': {
      id: '/luxury-hair-salon-spring-hill-tn'
      path: '/luxury-hair-salon-spring-hill-tn'
      fullPath: '/luxury-hair-salon-spring-hill-tn'
      preLoaderRoute: typeof LuxuryHairSalonSpringHillTnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hair-and-esthetic-services-spring-hill-tn': {
      id: '/hair-and-esthetic-services-spring-hill-tn'
      path: '/hair-and-esthetic-services-spring-hill-tn'
      fullPath: '/hair-and-esthetic-services-spring-hill-tn'
      preLoaderRoute: typeof HairAndEstheticServicesSpringHillTnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blonding-specialist-spring-hill-tn': {
      id: '/blonding-specialist-spring-hill-tn'
      path: '/blonding-specialist-spring-hill-tn'
      fullPath: '/blonding-specialist-spring-hill-tn'
      preLoaderRoute: typeof BlondingSpecialistSpringHillTnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/balayage-spring-hill-tn': {
      id: '/balayage-spring-hill-tn'
      path: '/balayage-spring-hill-tn'
      fullPath: '/balayage-spring-hill-tn'
      preLoaderRoute: typeof BalayageSpringHillTnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BalayageSpringHillTnRoute: BalayageSpringHillTnRoute,
  BlondingSpecialistSpringHillTnRoute: BlondingSpecialistSpringHillTnRoute,
  BookingRoute: BookingRoute,
  ContactRoute: ContactRoute,
  EducationRoute: EducationRoute,
  GalleryRoute: GalleryRoute,
  HairAndEstheticServicesSpringHillTnRoute:
    HairAndEstheticServicesSpringHillTnRoute,
  LuxuryHairSalonSpringHillTnRoute: LuxuryHairSalonSpringHillTnRoute,
  ScalpFacialSpringHillTnRoute: ScalpFacialSpringHillTnRoute,
  ServicesRoute: ServicesRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
