/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ScalpFacialSpringHillTnRouteImport } from './routes/scalp-facial-spring-hill-tn'
import { Route as LuxuryHairSalonSpringHillTnRouteImport } from './routes/luxury-hair-salon-spring-hill-tn'
import { Route as HairAndEstheticServicesSpringHillTnRouteImport } from './routes/hair-and-esthetic-services-spring-hill-tn'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as BlondingSpecialistSpringHillTnRouteImport } from './routes/blonding-specialist-spring-hill-tn'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BalayageSpringHillTnRouteImport } from './routes/balayage-spring-hill-tn'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesScalpRouteImport } from './routes/services.scalp'
import { Route as ServicesHairRouteImport } from './routes/services.hair'
import { Route as ServicesEstheticsRouteImport } from './routes/services.esthetics'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ScalpFacialSpringHillTnRoute = ScalpFacialSpringHillTnRouteImport.update({
  id: '/scalp-facial-spring-hill-tn',
  path: '/scalp-facial-spring-hill-tn',
  getParentRoute: () => rootRouteImport,
} as any)
const LuxuryHairSalonSpringHillTnRoute =
  LuxuryHairSalonSpringHillTnRouteImport.update({
    id: '/luxury-hair-salon-spring-hill-tn',
    path: '/luxury-hair-salon-spring-hill-tn',
    getParentRoute: () => rootRouteImport,
  } as any)
const HairAndEstheticServicesSpringHillTnRoute =
  HairAndEstheticServicesSpringHillTnRouteImport.update({
    id: '/hair-and-esthetic-services-spring-hill-tn',
    path: '/hair-and-esthetic-services-spring-hill-tn',
    getParentRoute: () => rootRouteImport,
  } as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const BlondingSpecialistSpringHillTnRoute =
  BlondingSpecialistSpringHillTnRouteImport.update({
    id: '/blonding-specialist-spring-hill-tn',
    path: '/blonding-specialist-spring-hill-tn',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BalayageSpringHillTnRoute = BalayageSpringHillTnRouteImport.update({
  id: '/balayage-spring-hill-tn',
  path: '/balayage-spring-hill-tn',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesScalpRoute = ServicesScalpRouteImport.update({
  id: '/scalp',
  path: '/scalp',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesHairRoute = ServicesHairRouteImport.update({
  id: '/hair',
  path: '/hair',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesEstheticsRoute = ServicesEstheticsRouteImport.update({
  id: '/esthetics',
  path: '/esthetics',
  getParentRoute: () => ServicesRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/balayage-spring-hill-tn': typeof BalayageSpringHillTnRoute
  '/blog': typeof BlogRouteWithChildren
  '/blonding-specialist-spring-hill-tn': typeof BlondingSpecialistSpringHillTnRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/hair-and-esthetic-services-spring-hill-tn': typeof HairAndEstheticServicesSpringHillTnRoute
  '/luxury-hair-salon-spring-hill-tn': typeof LuxuryHairSalonSpringHillTnRoute
  '/scalp-facial-spring-hill-tn': typeof ScalpFacialSpringHillTnRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/esthetics': typeof ServicesEstheticsRoute
  '/services/hair': typeof ServicesHairRoute
  '/services/scalp': typeof ServicesScalpRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/balayage-spring-hill-tn': typeof BalayageSpringHillTnRoute
  '/blog': typeof BlogRouteWithChildren
  '/blonding-specialist-spring-hill-tn': typeof BlondingSpecialistSpringHillTnRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/hair-and-esthetic-services-spring-hill-tn': typeof HairAndEstheticServicesSpringHillTnRoute
  '/luxury-hair-salon-spring-hill-tn': typeof LuxuryHairSalonSpringHillTnRoute
  '/scalp-facial-spring-hill-tn': typeof ScalpFacialSpringHillTnRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/esthetics': typeof ServicesEstheticsRoute
  '/services/hair': typeof ServicesHairRoute
  '/services/scalp': typeof ServicesScalpRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/balayage-spring-hill-tn': typeof BalayageSpringHillTnRoute
  '/blog': typeof BlogRouteWithChildren
  '/blonding-specialist-spring-hill-tn': typeof BlondingSpecialistSpringHillTnRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/hair-and-esthetic-services-spring-hill-tn': typeof HairAndEstheticServicesSpringHillTnRoute
  '/luxury-hair-salon-spring-hill-tn': typeof LuxuryHairSalonSpringHillTnRoute
  '/scalp-facial-spring-hill-tn': typeof ScalpFacialSpringHillTnRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/esthetics': typeof ServicesEstheticsRoute
  '/services/hair': typeof ServicesHairRoute
  '/services/scalp': typeof ServicesScalpRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/balayage-spring-hill-tn'
    | '/blog'
    | '/blonding-specialist-spring-hill-tn'
    | '/booking'
    | '/contact'
    | '/gallery'
    | '/hair-and-esthetic-services-spring-hill-tn'
    | '/luxury-hair-salon-spring-hill-tn'
    | '/scalp-facial-spring-hill-tn'
    | '/services'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/services/esthetics'
    | '/services/hair'
    | '/services/scalp'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/balayage-spring-hill-tn'
    | '/blog'
    | '/blonding-specialist-spring-hill-tn'
    | '/booking'
    | '/contact'
    | '/gallery'
    | '/hair-and-esthetic-services-spring-hill-tn'
    | '/luxury-hair-salon-spring-hill-tn'
    | '/scalp-facial-spring-hill-tn'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/services/esthetics'
    | '/services/hair'
    | '/services/scalp'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/balayage-spring-hill-tn'
    | '/blog'
    | '/blonding-specialist-spring-hill-tn'
    | '/booking'
    | '/contact'
    | '/gallery'
    | '/hair-and-esthetic-services-spring-hill-tn'
    | '/luxury-hair-salon-spring-hill-tn'
    | '/scalp-facial-spring-hill-tn'
    | '/services'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/services/esthetics'
    | '/services/hair'
    | '/services/scalp'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BalayageSpringHillTnRoute: typeof BalayageSpringHillTnRoute
  BlogRoute: typeof BlogRouteWithChildren
  BlondingSpecialistSpringHillTnRoute: typeof BlondingSpecialistSpringHillTnRoute
  BookingRoute: typeof BookingRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  HairAndEstheticServicesSpringHillTnRoute: typeof HairAndEstheticServicesSpringHillTnRoute
  LuxuryHairSalonSpringHillTnRoute: typeof LuxuryHairSalonSpringHillTnRoute
  ScalpFacialSpringHillTnRoute: typeof ScalpFacialSpringHillTnRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scalp-facial-spring-hill-tn': {
      id: '/scalp-facial-spring-hill-tn'
      path: '/scalp-facial-spring-hill-tn'
      fullPath: '/scalp-facial-spring-hill-tn'
      preLoaderRoute: typeof ScalpFacialSpringHillTnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luxury-hair-salon-spring-hill-tn': {
      id: '/luxury-hair-salon-spring-hill-tn'
      path: '/luxury-hair-salon-spring-hill-tn'
      fullPath: '/luxury-hair-salon-spring-hill-tn'
      preLoaderRoute: typeof LuxuryHairSalonSpringHillTnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hair-and-esthetic-services-spring-hill-tn': {
      id: '/hair-and-esthetic-services-spring-hill-tn'
      path: '/hair-and-esthetic-services-spring-hill-tn'
      fullPath: '/hair-and-esthetic-services-spring-hill-tn'
      preLoaderRoute: typeof HairAndEstheticServicesSpringHillTnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blonding-specialist-spring-hill-tn': {
      id: '/blonding-specialist-spring-hill-tn'
      path: '/blonding-specialist-spring-hill-tn'
      fullPath: '/blonding-specialist-spring-hill-tn'
      preLoaderRoute: typeof BlondingSpecialistSpringHillTnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/balayage-spring-hill-tn': {
      id: '/balayage-spring-hill-tn'
      path: '/balayage-spring-hill-tn'
      fullPath: '/balayage-spring-hill-tn'
      preLoaderRoute: typeof BalayageSpringHillTnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/scalp': {
      id: '/services/scalp'
      path: '/scalp'
      fullPath: '/services/scalp'
      preLoaderRoute: typeof ServicesScalpRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/hair': {
      id: '/services/hair'
      path: '/hair'
      fullPath: '/services/hair'
      preLoaderRoute: typeof ServicesHairRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/esthetics': {
      id: '/services/esthetics'
      path: '/esthetics'
      fullPath: '/services/esthetics'
      preLoaderRoute: typeof ServicesEstheticsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ServicesRouteChildren {
  ServicesEstheticsRoute: typeof ServicesEstheticsRoute
  ServicesHairRoute: typeof ServicesHairRoute
  ServicesScalpRoute: typeof ServicesScalpRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesEstheticsRoute: ServicesEstheticsRoute,
  ServicesHairRoute: ServicesHairRoute,
  ServicesScalpRoute: ServicesScalpRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BalayageSpringHillTnRoute: BalayageSpringHillTnRoute,
  BlogRoute: BlogRouteWithChildren,
  BlondingSpecialistSpringHillTnRoute: BlondingSpecialistSpringHillTnRoute,
  BookingRoute: BookingRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  HairAndEstheticServicesSpringHillTnRoute:
    HairAndEstheticServicesSpringHillTnRoute,
  LuxuryHairSalonSpringHillTnRoute: LuxuryHairSalonSpringHillTnRoute,
  ScalpFacialSpringHillTnRoute: ScalpFacialSpringHillTnRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
